marketplace: "BE"
domain: "amazon.co.uk"
mons_sel_mkid: "amzn1.mp.o.AMEN7PMS3EDWL"
urls:
  home: "https://sellercentral.amazon.co.uk/home?mons_sel_dir_mcid=amzn1.merchant.d.ACZ7PCS7ZFNLIG5FCI4V42CNVT3Q&mons_sel_mkid=amzn1.mp.o.AMEN7PMS3EDWL&mons_sel_dir_paid=amzn1.pa.d.ABZ3RRT3N67VQJCGDT4JRY5T2SRQ&ignore_selection_changed=true"
  add_product_entry: "https://sellercentral.amazon.co.uk/abis/listing/create/product_identity?productType=SCREEN_PROTECTOR&productData=%7B%22sparseText%22%3A%22screen+protector%22%7D&recommendedBrowseNodeId=27863027031&displayPath=High-tech%2FT%C3%A9l%C3%A9phones+portables+et+communication%2FAccessoires%2FMaintenance%2C+entretien+et+r%C3%A9parations%2FProtections+d%27%C3%A9cran#product_identity"
  item_type_keyword: "High-tech > Téléphones portables et communication > Accessoires > Maintenance, entretien et réparations > Protections d'écran"
