marketplace: "ES"
domain: "amazon.co.uk"
mons_sel_mkid: "amzn1.mp.o.A1RKKUPIHCS9HS"
urls:
  home: "https://sellercentral.amazon.co.uk/home?mons_sel_mkid=amzn1.mp.o.A1RKKUPIHCS9HS&mons_sel_dir_mcid=amzn1.merchant.d.ACZ7PCS7ZFNLIG5FCI4V42CNVT3Q&mons_sel_dir_paid=amzn1.pa.d.ABZ3RRT3N67VQJCGDT4JRY5T2SRQ&ignore_selection_changed=true"
  add_product_entry: "https://sellercentral.amazon.co.uk/abis/listing/create/product_identity?productType=SCREEN_PROTECTOR&productData=%7B%22sparseText%22%3A%22screen+protector%22%7D&recommendedBrowseNodeId=934190031&displayPath=Electr%C3%B3nica%2FComunicaci%C3%B3n+m%C3%B3vil+y+accesorios%2FAccesorios%2FMantenimiento%2C+cuidado+y+reparaciones%2FProtectores+de+pantalla#product_identity"
  item_type_keyword: "Electrónica > Comunicación móvil y accesorios > Accesorios > Mantenimiento, cuidado y reparaciones > Protectores de pantalla"
