marketplace: "SE"
domain: "amazon.co.uk"
mons_sel_mkid: "amzn1.mp.o.A2NODRKZP88ZB9"
urls:
  home: "https://sellercentral.amazon.co.uk/home?mons_sel_dir_mcid=amzn1.merchant.d.ACZ7PCS7ZFNLIG5FCI4V42CNVT3Q&mons_sel_mkid=amzn1.mp.o.A2NODRKZP88ZB9&mons_sel_dir_paid=amzn1.pa.d.ABZ3RRT3N67VQJCGDT4JRY5T2SRQ&ignore_selection_changed=true"
  add_product_entry: "https://sellercentral.amazon.co.uk/abis/listing/create/product_identity?productType=SCREEN_PROTECTOR&productData=%7B%22sparseText%22%3A%22screen+protector%22%7D&recommendedBrowseNodeId=20637844031&displayPath=Elektronik%2FMobiler+%26+tillbeh%C3%B6r%2FTillbeh%C3%B6r%2FUnderh%C3%A5ll%2C+v%C3%A5rd+%26+reparationer%2FSk%C3%A4rmskydd#product_identity"
  item_type_keyword: "Elektronik > Mobiler & tillbehör > Tillbehör > Underhåll, vård & reparationer > Skärmskydd"
